CREATE DATABASE novaxcypher;

USE novaxcypher;

CREATE TABLE users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100),
 email VARCHAR(100),
 idea TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);